name: CI Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup node and pnpm
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: node version
        run: node -v
      - name: pnpm version
        run: pnpm -v
      - name: pnpm install, test and build
        run: |
          pnpm install
          pnpm test
          pnpm build
        env:
          CI: true
